version: '3'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./web-root:/var/www/html
    depends_on:
      - webserver
    restart: "no"
    env_file: .env
    command: certonly --webroot --webroot-path=/var/www/html --email leap-lab@psych.rutgers.edu --agree-tos --no-eff-email --force-renewal -d $DOMAIN
